// import Head from 'next/head'
// import { Layout } from 'components'
// import { RotaAutenticada } from 'components'

// function Home() {
  
//   return (

//     <RotaAutenticada >
//       <Head>
//         <title>Animais Silvestres</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <Layout titulo="Home">

//       </Layout >
//     </RotaAutenticada>

//   )
// }

// export default Home

import type { NextPage } from "next";
import VLibras from "vlibras-nextjs";

const Home: NextPage = () => {
  return (
      <div>
        {/* only worked in production in tests with nextjs applications maybe you can solve this! */}
        {process.env.NODE_ENV === "production" && <VLibras forceOnload />}
    </div>
  );
};

export default Home;