export { useCidadeService} from './cidade.service'
export { usePaisesService} from './paises.service'
export { useAnimaisService} from './animais.service'
export { useGrupoService } from './grupos.service'
export { useUsuarioService } from './usuario.service'
export { useEspecieService } from './especie.service'
export { useClassificacaoService } from './classificacao.service'