export { useCidadeService} from './cidade.service'
export { useEstadioService} from './estadio.service'
export { useCampeonatoService} from './campeonato.service'
export { useEquipeService } from './equipe.service'
export { useUsuarioService } from './usuario.service'
export { useEmpresaService } from './empresas.service'